- sentryext/ext.go
- seqgenext/ext.go
没有办法直接从app.Get取出的Extension转成ext对应的struct，需要interface转一次。应该用Object方法来完成这个事情。
> fix ext Object

- app.go
1. 只是Get，没有加锁的必要
2. 影响了初始化阶段，一个ext引用另一个ext。因为app.Init时已经加锁，这时想要取一个ext就会卡住。
> fix get ext lock

- cachext/cached.go
- cachext/ext.go
- cachext/ext_test.go
反射获取函数名只能拿到函数顺序，实际使用中容易引起问题。例如：调整函数顺序时，会导致不同函数key互相重叠。
现有用法：
```go
// package models
var (
cachedFunc1 *cachext.CacheOption
cachedFunc2 *cachext.CacheOption
)
func InitCache(){
// 如果这里添加另外的定义，会使用func1的cachekey，引起错乱
cachedFunc1, _ := cache.Cached(func([]string, []int64)(interface{}, error){...}, cachext.SetTTL(10*time.Hour))
cachedFunc2, _ := cache.Cached(func([]string, []int64)(interface{}, error){...},  cachext.SetTTL(10*time.Hour))
}
```
现在调整一下创建CachedFunc的方式，用法如下：
```go
// package models
var (
cachedFunc1 *cachext.CacheOption
cachedFunc2 *cachext.CacheOption
)
func InitCache(){
cachedFunc1, _ := cache.Cached("func1", func([]string, []int64)(interface{}, error){...},  cachext.SetTTL(10*time.Hour))
cachedFunc2, _ := cache.Cached("func2", func([]string, []int64)(interface{}, error){...}, …
```
> 调整CachedFunc的用法

- cachext/backend/memory/memory.go
- cachext/backend/redis/redis.go
- cachext/cached.go
- cachext/ext.go
- cachext/ext_test.go
- esapmext/ext.go
- go.mod
- go.sum
- gormext/ext.go
cachext & gormext with apm useage:(**TEST ENV:  KIBANA:6.5.0 APM_SERVER:6.5.0**)
```yaml
// config.yaml
elastic_apm_enable: true
```
```go
// models.go
require "go.elastic.co/apm/module/apmgorm"
func WordLogAggCheckExist(ctx context.Context, userId uint64, vocabIds []uint64) (interface{}, error) {
apmDB := apmgorm.WithContext(ctx, myapp.DB) // ctx from handlers
apmDB.Where(...).Find(...)
return nil, nil
}
```
```go
//models.go
cachedFunc = myapp.Cache.Cached(
"cacheFuncCacheKey",
func(ctx context.Context, strArgs []string, intArgs []int64) (interface{}, error) {
return WordLogAggCheckExist(ctx, intArgs[0], intArgs[1:])
},
cachext.WithTTL(12*time.Hour),
)
cachedFunc.GetResult(ctx, &out, []string{}, []int64{})  // ctx from handlers
apmCache := myapp.Cache.WithContext(ctx)  // ctx from …
```
> Add apm support for cachext & gormext

- extensions/redisext/ext.go
为了使APM能够跟踪redis的操作，把redis.Client的WithContext方法暴露出来。
```
redisExt = app.RedisExt.WithContext(ctx) // ctx 来自server
redisExt.Get("key")
```
> Add RedisExt WithContext

- extensions/entext/ext.go
ent目前功能有限，有些场景不能很好的支持，比如主键名称必须为 `id`。而目前项目中存在主键不是`id`的表。添加DB方法供使用者执行sql。
> Add DB() to ent

- extensions/cachext/backend/memory/memory.go
- extensions/cachext/backend/redis/redis.go
- extensions/cachext/cached.go
- extensions/cachext/ext.go
- extensions/cachext/ext_test.go
- 把context作为参数传递更加符合context的定位。
- WithContext 由于不调用也能正常使用cache，因此很容易忘记写，进而导致apm无法跟踪cache。
```go
// 改动之前
cache := app.Cache.WithContext(ctx)
cache.Set("some cache key", "some value")
// 改之后
cache.Set(ctx, "some cache key", "some value")
```
> Remove WithContext from cachext

- go.mod
- go.sum
这一次更新把`event := NewEvent()`删除掉了，导致event里面的内容没有被初始化。我们用了extra的时候会发现这个问题。需要先锁死sentry-go版本等修复。
https://github.com/getsentry/sentry-go/pull/185/files
> fix sentry go

- extensions/redisext/ext.go
- extensions/redisext/ext_test.go
强制使用`.Client(ctx)`方法来确保一定传了context
> redis with context

- go.mod
- go.sum
> Revert "Bump github.com/getsentry/sentry-go from 0.5.1 to 0.6.0"

- extensions/cachext/backend/memory/memory.go
- extensions/cachext/backend/redis/redis.go
- extensions/cachext/ext.go
现在init ext的时候会覆盖旧的backend的redis实例，改为每次Init ext的时候给一个新的backend
> fix cache ext

- extensions/esapmext/ext.go
初始化EsApmExt中的tracer时，tracer可以为nil， 但是关闭EsApmExt的时候tracer为空会报错
> fix: close nil apm trace

- extensions/sentryext/openapi/mw.go
目前可以配置`sentry_repanic: true`来做到，但默认是false。其实大多数情况下都是sentry捕获完希望能再抛出来的。
> openapi sentry mw: default repanic

- cmd/gobay/templates/app/extensions.go.tmpl
- cmd/gobay/templates/app/grpc/handlers.go.tmpl
- cmd/gobay/templates/app/openapi/handlers.go.tmpl
- cmd/gobay/templates/spec/enttmpl/client.tmpl
- docs/CHANGELOG.md
- extensions/cachext/backend/memory/memory.go
- extensions/cachext/backend/redis/redis.go
- extensions/cachext/ext.go
- extensions/cachext/ext_test.go
- extensions/redisext/ext.go
- extensions/redisext/ext_test.go
-------------------------------------------
要使用的话，在GRPC和OpenAPI的 health check controller里，添加触发每种health check的逻辑
```go
if checkType == "liveness" || checkType == "readiness" {
ctx := params.HTTPRequest.Context()
if app.EntExt != nil {
if err := app.EntClient.CheckHealth(ctx); err != nil {
return health.NewHealthCheckNotFound()
}
}
if app.Redis != nil {
if err := app.Redis.CheckHealth(ctx); err != nil {
return health.NewHealthCheckNotFound()
}
}
if app.Cache != nil {
if err := app.Cache.CheckHealth(ctx); err != nil {
return health.NewHealthCheckNotFound()
}
}
return health.NewHealthCheckOK()
}
```
-------------------------------------------
Cache 和 Redis:
extension 内添加 CheckHealth function , 
比如 `app.Cache.CheckHealth(ctx)` 就会在extension内调用 set -> get -> delete 缓存，来测试缓存使用是否正常。 …
> enhance healthcheck

- extensions/sentryext/grpc/mw.go
对于 grpc server，sentry 在 recover 时增加打印到标准输出的操作
> feature(log): log panic stack trace to stdout in sentry recovery

- cmd/gobay/templates/spec/enttmpl/client.tmpl
`.Only()`会出问题。`.All()`才安全。
需要修改一下ent template。
> hotfix health check ent template

- cmd/gobay/templates/.golangci.yml
- cmd/gobay/templates/.pre-commit-config.yaml
- cmd/gobay/templates/Makefile.tmpl
启用了下面的 golangci-lint 插件（下面是额外启用的插件，golangci-lint 本身就启用了一些）：
```
- goimports  # import 顺序
- misspell   # 英文拼写错误检查
- gofumpt    # 一些写法的格式化：多余空行、变量定义、大括号位置等
- gofmt      # 之前就在使用的 gofmt
- gocritic   # 一些更严格的代码风格检查。注意，这个插件的告警无法自动修复，必须手动修改
```
pre-commit 的时候自动修复可以修复的部分。
Makefile 里增加了一个 `make lintfix` 命令，在本地可以执行这个修复代码（gocritic 除外）。
生成完项目本地开发的时候，需要本地更新一下 golangci-lint 版本：
```
go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.35.2
```
没有挂 pre-commit 勾子的需要挂一下：
```
pre-commit install
```
> better lint

- .github/workflows/ci.yml
- extensions/busext/amqp.go
冲突的逻辑都在这个文件里，下面的问题描述的代码行数指这个文件的行数 https://github.com/streadway/amqp/blob/master/confirms.go
如果 channel 的 buffer 为 1，在弱网环境下可能之前发的消息没有收到 ack，所以在某一刻能可能发生这样的事件顺序：
1. 收到 ack，调用 61 行的 `One` 方法 -> `resequence` 调用 `confirm` 方法丢消息到 channel
2. 又收到一条 ack，调用 61 行的 `One` 方法 -> 取锁 -> `resequence` 调用 `confirm` 方法 -> 第 45 行尝试丢消息到 channel -> channel 阻塞（没有释放锁）
3. 我们正在主动发消息，走到 31 行的 `Publish` 方法 -> 取锁失败
这个时候就会一直阻塞住；简单来说是因为 buffer 是 1 但是同时收到两条 ack（虽然我们发消息是串行发的，但是确实能复现这种极端情况）。
尝试如果把 buffer 加到 5，在 10% 丢包率、延时 500ms 的弱网环境下尝试复现，不停地发消息跑了一小段时间并没有复现成功（如果 buffer 为 1 不停地发消息基本可以在一分钟内复现卡死）。可以认为收到 5 条的可能性是极小的。
---
缺点是弱网有延迟情况下，我们 ack 的那条可能就不是发的那一条了（虽然现在一样是不能确定的）
所以这个 PR 相比现状是没有损失的，而且解决了卡掉的问题
---
一个更好的解决方案是给 amqp 库提 PR 让 Publish （仅仅是一个自增）不要取锁而是使用 atomic
https://github.com/streadway/amqp/pull/508
> 尝试修复弱网环境时，同时收到两条ack消息往channel丢导致的阻塞问题

- docs/CHANGELOG.md
- extensions/cachext/cached.go
- extensions/cachext/ext.go
- extensions/cachext/ext_test.go
原来的 cachenil 逻辑有错误，会导致实际上只有一种情况会返回 cachext.Nil，即命中了 cache 且 cache 里存的是 msgpack nil 值；其他情况都不会。详见这里 https://github.com/shanbay/gobay/pull/363
---
如果改回正确的响应值，会和现状产生一个比较大的差异：改完了以后即使没有 WithCacheNil 同样可能返回 `cachext.Nil`。
而我们使用时都没有做过这个处理，改动起来会很大，所以干脆删除掉这个逻辑，让使用者在之前使用 WithCacheNil 的地方改为自行判断值是不是空值，这样改动会小得多。
> rm cachenil

- app.go
- extensions/busext/amqp.go
- extensions/busext/amqp_test.go
- testdata/config.yaml
在测试busext时，发现config中传入的配置没有生效。其他ext如果在init时设置默认值，也有问题。
`GetConfigByPrefix`中使用`subConfig.SetDefault( )`读取配置，给相应变量设置默认值之后，又会被extension初始化时设置的默认值替换掉。按照viper的配置优先级，读取配置应该直接`Set`，在ext初始化时，使用`SetDefault`。
> Fix: config overwritten by default values

- docs/CHANGELOG.md
- extensions/cachext/backend/redis/v9/redis.go
- extensions/redisext/ext.go
- extensions/redisext/v9/ext.go
- extensions/seqgenext/ext.go
- go.mod
- go.sum
因为有 `go-redis@v6` 和 `go-redis@v9` 共存，在使用到 `redis` 的 extension 内新增抽象隐藏不同 `go-redis` 版本上的差异
> feat: abstract redis

- docs/CHANGELOG.md
- extensions/entext/ext.go
带占位符的 SQL 执行流程为 prepared -> execute -> close 客户端将该语句和参数发给 mysql 编译成一个 prepared 语句，如果设置 `interpolateparams=true` 可以减少 prepared 请求，SQL 语句在客户端完成拼接。在 `go-sql-driver/mysql` 库中 如果发现没有设置该参数，会返回一个 `ErrSkip` 被 otelsql 捕捉，可以通过配置 `DisableErrSkip` 忽略这个报错，因为只是优化项不影响后续流程。但有实验表明 `interpolateparams=true` 能提高 QPS 18%，可以考虑在 DSN 中增加该参数
https://github.com/go-sql-driver/mysql/blob/f6a18cf1ac3e6bc282f72874a3742469a99e5762/connection.go#L327
> feat: config DisableErrSkip
